sonar.projectKey=pyroguard-sl
sonar.projectName=PyroGuard SL
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**,**/shared_data/**,backend/app/data/**,frontend/public/favicon.svg
sonar.host.url=http://localhost:9000/sonar
sonar.login=admin
sonar.password=admin123
sonar.sourceEncoding=UTF-8
